### ISSUE TITLE
Phone Numbers

### ISSUE THREAD

**Issue by sushi-buffer** [exercism/clojurescript#85]
There are some finicky test expectations in this exercise.

Let's consider that the exercise expect numbers to conform to the following:

The format is usually represented as

```
(NXX)-NXX-XXXX
```

where N is any digit from 2 through 9 and X is any digit from 0 through 9.

Now we have a test cases that fails (correctly) for numbers with invalid lengths:

```clojure
(deftest invalid-when-9-digits
  (is (= "0000000000" (phone-number/number "123456789"))))
```

...aaand a test that fails for an 11-digit number with an incorrect first number in the leftmost group  (should be 1):

```clojure
(deftest invalid-when-11-digits
  (is (= "0000000000" (phone-number/number "21234567890"))))
```

Then we have a curveball like this. A test that actually expects to return a valid number for 10-digit number that starts with 1, although the instructions describe such numbers to be invalid:

```clojure
(deftest cleans-number
  (is (= "1234567890" (phone-number/number "(123) 456-7890"))))
```

Isn't this a bit inconsistent considering the rules? The tests for same exercise on Clojure-track correctly differentiates from valid and invalid numbers and expect the function to return `"0000000000"` in a case like above.

**Comment by kotp** [comment]
The [canonical data file for these tests](https://github.com/exercism/problem-specifications/blob/main/exercises/phone-number/canonical-data.json) show that the tests for area code that starts with 1 should fail.  (And that is correct for the NANP).

So it appears (by reading the tests) that the following tests are incorrect:

- `deftest cleans-number`
- `deftest area-code`
- `deftest area-code-with-full-us-phone-number`

Thanks for noticing this @4lph4-Ph4un !

Would you be interested in making a pull request that makes the tests match what is provided in the canonical test description file?

**Comment by ghost** [comment]
It looks like I might have time to make those changes perhaps on Tuesday, or if I'm lucky, maybe tomorrow. So yeah, if that's okay I might take a stab at it! Haven't contributed to Exercism before, so this could be a good starting point. Also, if this is urgent, I don't mind if someone gets this done before me!

**Comment by kotp** [comment]
I am sure it is not urgent.  So you are welcome to do it.

**Comment by ghost** [comment]
Heeere we go... https://github.com/exercism/clojurescript/pull/87

**Comment by kotp** [comment]
@4lph4-Ph4un If you want to mark in a commit for #87 that it closes this issue, it will automatically close this one when it is accepted into the main branch.
